### ISSUE TITLE
How do I know it has worked!

### ISSUE THREAD

**Issue by williamsdb** [fgth/cachet-uptime-robot-py27#1]
Hi

Thanks for releasing this. Just done a setup and run:

    python27 update_status.py config.ini

nothing is return in the way of error messages and I can see that there is nothing in the metric_points table.

How can I tell if it is working?

Thanks

**Comment by fsoyer** [comment]
Have you tried debug=True in script ? You must at least have some messages.

**Comment by fsoyer** [comment]
I've updated the README with some tips to troubleshoot the accesses.

**Comment by williamsdb** [comment]
Hi, tried with debug and it created a record and will leave it over the weekend to see what happens. Thanks!

**Comment by fsoyer** [comment]
OK, my bad. Wanting to do well I did worse. I've solved bug in a "if debug" block, should work now.
